Logging:
  Elastic.Apm: "Warning"
ElasticApm:
  ServiceName: Policies.Search.Service
  ServerUrl: http://apm-server:8200
  Environment: production
  CaptureBody: all
  TransactionSampleRate: 1.0
Logstash:
  Uri: http://logstash:28080
  ServiceName: Policies.Search.Service
  Environment: production
OtelCollector:
  Endpoint: http://jaeger:4317
  ServiceName: Policies.Search.Service
ElasticSearch:
  Hosts:
    - http://elasticsearch:9200
  UserName: elastic
  Password: elastic
Kafka:
  BootstrapServers: kafka:9092
  Producers:
    Events:
      GroupId: policy.search.events.consumer.group
      Topics:
      - Policy: policy.events