OtelCollector:
  Endpoint: http://jaeger:4317
  ServiceName: Policies.Search.Service
ElasticSearch:
  Hosts:
    - http://elasticsearch:9200
Kafka:
  BootstrapServers: kafka:9092
  Producers:
    Events:
      GroupId: policy.search.events.consumer.group
      Topics:
      - Policy: policy.events