Logging:
  Elastic.Apm: "Warning"
ElasticApm:
  ServiceName: Pricing.Service
  ServerUrl: http://apm-server:8200
  Environment: production
  CaptureBody: all
  TransactionSampleRate: 1.0
Logstash:
  Uri: http://logstash:28080
  ServiceName: Pricing.Service
  Environment: production
OtelCollector:
  Endpoint: http://jaeger:4317
  ServiceName: Pricing.Service
ConnectionStrings:
  PricingConnection: Host=postgres;Port=5432;Database=Microservices.Demo.Pricing;Username=postgres;Password=Password1234